# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19rJwOw57t7asxX0JS5AUlBkXXttX7hoU
"""

def tashxis(belgi):
  if belgi == "istima":
     return "Parasetamol iching"
  elif belgi == "bosh og'riq":
      return "trimol iching"
  elif belgi == "tish og'riq":
      return "quepen iching"
  else:
      return "Shifokorga murojaat qiling"
belgi=input("Kasallik belgisini kiriting ")
natija=tashxis(belgi)
print(natija)